package com.javamentor.qa.platform.service.impl;


import com.javamentor.qa.platform.models.entity.user.Role;
import com.javamentor.qa.platform.models.entity.user.User;
import com.javamentor.qa.platform.service.impl.dto.RoleService;
import com.javamentor.qa.platform.service.impl.dto.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;

@Service
public class TestDataInitService {
    private UserService userService;
    private RoleService roleService;

    @Autowired
    public TestDataInitService(UserService userService, RoleService roleService) {
        this.roleService = roleService;
        this.userService = userService;
    }

    @Transactional
    public void createEntity() {
        createUserEntity();
    }

    private void createUserEntity() {
        Role adminRole = new Role("ROLE_ADMIN");
        Role userRole = new Role ("ROLE_USER");

        User admin = new User();
        admin.setEmail("admin@admin.com");
        admin.setPassword("admin");
        admin.setFullName("John Smith");
        admin.setPersistDateTime(LocalDateTime.now());
        admin.setIsEnabled(true);
        admin.setCity("CitiName");
        admin.setImageLink("image.link.com");
        admin.setLinkSite("sitename.admin.com");
        admin.setLinkGitHub("admin.github.com");
        admin.setLinkVk("vk.com/admin");
        admin.setAbout("It'sa me, Mario!");
        admin.setNickname("IamTheLaw");
        admin.setLastUpdateDateTime(LocalDateTime.now());
        admin.setRole(adminRole);
        userService.persist(admin);

        User user1 = new User();
        user1.setEmail("user1@user.com");
        user1.setPassword("admin1");
        user1.setFullName(" User user1");
        user1.setPersistDateTime(LocalDateTime.now());
        user1.setIsEnabled(true);
        user1.setCity("CitiName1");
        user1.setImageLink("user1.image.link.com");
        user1 .setLinkSite("sitename.user1.com");
        user1 .setLinkGitHub("user1.github.com");
        user1.setLinkVk("vk.com/user1");
        user1.setAbout("I am User1");
        user1.setNickname("user1NickName");
        user1 .setLastUpdateDateTime(LocalDateTime.now());
        user1.setRole(userRole);
        userService.persist(user1);

        User user2 = new User();
        user2.setEmail("user2@user.com");
        user2.setPassword("admin2");
        user2.setFullName(" User user2");
        user2.setPersistDateTime(LocalDateTime.now());
        user2.setIsEnabled(true);
        user2.setCity("CitiName2");
        user2.setImageLink("user2.image.link.com");
        user2 .setLinkSite("sitename.user2.com");
        user2 .setLinkGitHub("user2.github.com");
        user2.setLinkVk("vk.com/user2");
        user2.setAbout("I am User2");
        user2.setNickname("user2NickName");
        user2 .setLastUpdateDateTime(LocalDateTime.now());
        user2.setRole(userRole);
        userService.persist(user2);

        User user3 = new User();
        user3.setEmail("user3@user.com");
        user3.setPassword("admin3");
        user3.setFullName(" User user3");
        user3.setPersistDateTime(LocalDateTime.now());
        user3.setIsEnabled(true);
        user3.setCity("CitiName3");
        user3.setImageLink("user3.image.link.com");
        user3 .setLinkSite("sitename.user3.com");
        user3 .setLinkGitHub("user3.github.com");
        user3.setLinkVk("vk.com/user3");
        user3.setAbout("I am User3");
        user3.setNickname("user3NickName");
        user3 .setLastUpdateDateTime(LocalDateTime.now());
        user3.setRole(userRole);
        userService.persist(user3);

        User user4 = new User();
        user4.setEmail("user4@user.com");
        user4.setPassword("admin4");
        user4.setFullName(" User user4");
        user4.setPersistDateTime(LocalDateTime.now());
        user4.setIsEnabled(true);
        user4.setCity("CitiName4");
        user4.setImageLink("user4.image.link.com");
        user4 .setLinkSite("sitename.user4.com");
        user4 .setLinkGitHub("user4.github.com");
        user4.setLinkVk("vk.com/user4");
        user4.setAbout("I am User4");
        user4.setNickname("user4NickName");
        user4 .setLastUpdateDateTime(LocalDateTime.now());
        user4.setRole(userRole);
        userService.persist(user4);

        User user5 = new User();
        user5.setEmail("user5@user.com");
        user5.setPassword("admin5");
        user5.setFullName(" User user5");
        user5.setPersistDateTime(LocalDateTime.now());
        user5.setIsEnabled(true);
        user5.setCity("CitiName5");
        user5.setImageLink("user5.image.link.com");
        user5 .setLinkSite("sitename.user5.com");
        user5 .setLinkGitHub("user5.github.com");
        user5.setLinkVk("vk.com/user5");
        user5.setAbout("I am User5");
        user5.setNickname("user5NickName");
        user5 .setLastUpdateDateTime(LocalDateTime.now());
        user5.setRole(userRole);
        userService.persist(user5);

        User user6 = new User();
        user6.setEmail("user6@user.com");
        user6.setPassword("admin6");
        user6.setFullName(" User user6");
        user6.setPersistDateTime(LocalDateTime.now());
        user6.setIsEnabled(true);
        user6.setCity("CitiName6");
        user6.setImageLink("user6.image.link.com");
        user6 .setLinkSite("sitename.user6.com");
        user6 .setLinkGitHub("user6.github.com");
        user6.setLinkVk("vk.com/user6");
        user6.setAbout("I am User6");
        user6.setNickname("user6NickName");
        user6 .setLastUpdateDateTime(LocalDateTime.now());
        user6.setRole(userRole);
        userService.persist(user6);

        User user7 = new User();
        user7.setEmail("user7@user.com");
        user7.setPassword("admin7");
        user7.setFullName(" User user7");
        user7.setPersistDateTime(LocalDateTime.now());
        user7.setIsEnabled(true);
        user7.setCity("CitiName7");
        user7.setImageLink("user7.image.link.com");
        user7 .setLinkSite("sitename.user7.com");
        user7 .setLinkGitHub("user7.github.com");
        user7.setLinkVk("vk.com/user7");
        user7.setAbout("I am User7");
        user7.setNickname("user7NickName");
        user7 .setLastUpdateDateTime(LocalDateTime.now());
        user7.setRole(userRole);
        userService.persist(user7);

        User user8 = new User();
        user8.setEmail("user8@user.com");
        user8.setPassword("admin8");
        user8.setFullName(" User user8");
        user8.setPersistDateTime(LocalDateTime.now());
        user8.setIsEnabled(true);
        user8.setCity("CitiName8");
        user8.setImageLink("user8.image.link.com");
        user8 .setLinkSite("sitename.user8.com");
        user8 .setLinkGitHub("user8.github.com");
        user8.setLinkVk("vk.com/user8");
        user8.setAbout("I am User8");
        user8.setNickname("user8NickName");
        user8 .setLastUpdateDateTime(LocalDateTime.now());
        user8.setRole(userRole);
        userService.persist(user8);

        User user9 = new User();
        user9.setEmail("user9@user.com");
        user9.setPassword("admin9");
        user9.setFullName(" User user9");
        user9.setPersistDateTime(LocalDateTime.now());
        user9.setIsEnabled(true);
        user9.setCity("CitiName9");
        user9.setImageLink("user9.image.link.com");
        user9 .setLinkSite("sitename.user9.com");
        user9 .setLinkGitHub("user9.github.com");
        user9.setLinkVk("vk.com/user9");
        user9.setAbout("I am User9");
        user9.setNickname("user9NickName");
        user9 .setLastUpdateDateTime(LocalDateTime.now());
        user9.setRole(userRole);
        userService.persist(user9);

        User user10 = new User();
        user10.setEmail("user10@user.com");
        user10.setPassword("admin10");
        user10.setFullName(" User user10");
        user10.setPersistDateTime(LocalDateTime.now());
        user10.setIsEnabled(true);
        user10.setCity("CitiName10");
        user10.setImageLink("user10.image.link.com");
        user10 .setLinkSite("sitename.user10.com");
        user10 .setLinkGitHub("user10.github.com");
        user10.setLinkVk("vk.com/user10");
        user10.setAbout("I am User10");
        user10.setNickname("user10NickName");
        user10 .setLastUpdateDateTime(LocalDateTime.now());
        user10.setRole(userRole);
        userService.persist(user10);

        User user11 = new User();
        user11.setEmail("user11@user.com");
        user11.setPassword("admin11");
        user11.setFullName(" User user11");
        user11.setPersistDateTime(LocalDateTime.now());
        user11.setIsEnabled(true);
        user11.setCity("CitiName11");
        user11.setImageLink("user11.image.link.com");
        user11 .setLinkSite("sitename.user11.com");
        user11 .setLinkGitHub("user11.github.com");
        user11.setLinkVk("vk.com/user11");
        user11.setAbout("I am User11");
        user11.setNickname("user11NickName");
        user11 .setLastUpdateDateTime(LocalDateTime.now());
        user11.setRole(userRole);
        userService.persist(user11);

        User user12 = new User();
        user12.setEmail("user12@user.com");
        user12.setPassword("admin12");
        user12.setFullName(" User user12");
        user12.setPersistDateTime(LocalDateTime.now());
        user12.setIsEnabled(true);
        user12.setCity("CitiName12");
        user12.setImageLink("user12.image.link.com");
        user12 .setLinkSite("sitename.user12.com");
        user12 .setLinkGitHub("user12.github.com");
        user12.setLinkVk("vk.com/user12");
        user12.setAbout("I am User12");
        user12.setNickname("user12NickName");
        user12 .setLastUpdateDateTime(LocalDateTime.now());
        user12.setRole(userRole);
        userService.persist(user12);

        User user13 = new User();
        user13.setEmail("user13@user.com");
        user13.setPassword("admin13");
        user13.setFullName(" User user13");
        user13.setPersistDateTime(LocalDateTime.now());
        user13.setIsEnabled(true);
        user13.setCity("CitiName13");
        user13.setImageLink("user13.image.link.com");
        user13 .setLinkSite("sitename.user13.com");
        user13 .setLinkGitHub("user13.github.com");
        user13.setLinkVk("vk.com/user13");
        user13.setAbout("I am User13");
        user13.setNickname("user13NickName");
        user13 .setLastUpdateDateTime(LocalDateTime.now());
        user13.setRole(userRole);
        userService.persist(user13);

        User user14 = new User();
        user14.setEmail("user14@user.com");
        user14.setPassword("admin14");
        user14.setFullName(" User user14");
        user14.setPersistDateTime(LocalDateTime.now());
        user14.setIsEnabled(true);
        user14.setCity("CitiName14");
        user14.setImageLink("user14.image.link.com");
        user14 .setLinkSite("sitename.user14.com");
        user14 .setLinkGitHub("user14.github.com");
        user14.setLinkVk("vk.com/user14");
        user14.setAbout("I am User14");
        user14.setNickname("user14NickName");
        user14 .setLastUpdateDateTime(LocalDateTime.now());
        user14.setRole(userRole);
        userService.persist(user14);

        User user15 = new User();
        user15.setEmail("user15@user.com");
        user15.setPassword("admin15");
        user15.setFullName(" User user15");
        user15.setPersistDateTime(LocalDateTime.now());
        user15.setIsEnabled(true);
        user15.setCity("CitiName15");
        user15.setImageLink("user15.image.link.com");
        user15 .setLinkSite("sitename.user15.com");
        user15 .setLinkGitHub("user15.github.com");
        user15.setLinkVk("vk.com/user15");
        user15.setAbout("I am User15");
        user15.setNickname("user15NickName");
        user15 .setLastUpdateDateTime(LocalDateTime.now());
        user15.setRole(userRole);
        userService.persist(user15);

        User user16 = new User();
        user16.setEmail("user16@user.com");
        user16.setPassword("admin16");
        user16.setFullName(" User user16");
        user16.setPersistDateTime(LocalDateTime.now());
        user16.setIsEnabled(true);
        user16.setCity("CitiName16");
        user16.setImageLink("user16.image.link.com");
        user16 .setLinkSite("sitename.user16.com");
        user16 .setLinkGitHub("user16.github.com");
        user16.setLinkVk("vk.com/user16");
        user16.setAbout("I am User16");
        user16.setNickname("user16NickName");
        user16 .setLastUpdateDateTime(LocalDateTime.now());
        user16.setRole(userRole);
        userService.persist(user16);

        User user17 = new User();
        user17.setEmail("user17@user.com");
        user17.setPassword("admin17");
        user17.setFullName(" User user17");
        user17.setPersistDateTime(LocalDateTime.now());
        user17.setIsEnabled(true);
        user17.setCity("CitiName17");
        user17.setImageLink("user17.image.link.com");
        user17 .setLinkSite("sitename.user17.com");
        user17 .setLinkGitHub("user17.github.com");
        user17.setLinkVk("vk.com/user17");
        user17.setAbout("I am User17");
        user17.setNickname("user17NickName");
        user17 .setLastUpdateDateTime(LocalDateTime.now());
        user17.setRole(userRole);
        userService.persist(user17);

        User user18 = new User();
        user18.setEmail("user18@user.com");
        user18.setPassword("admin18");
        user18.setFullName(" User user18");
        user18.setPersistDateTime(LocalDateTime.now());
        user18.setIsEnabled(true);
        user18.setCity("CitiName18");
        user18.setImageLink("user18.image.link.com");
        user18 .setLinkSite("sitename.user18.com");
        user18 .setLinkGitHub("user18.github.com");
        user18.setLinkVk("vk.com/user18");
        user18.setAbout("I am User18");
        user18.setNickname("user18NickName");
        user18 .setLastUpdateDateTime(LocalDateTime.now());
        user18.setRole(userRole);
        userService.persist(user18);

        User user19 = new User();
        user19.setEmail("user19@user.com");
        user19.setPassword("admin19");
        user19.setFullName(" User user19");
        user19.setPersistDateTime(LocalDateTime.now());
        user19.setIsEnabled(true);
        user19.setCity("CitiName19");
        user19.setImageLink("user19.image.link.com");
        user19 .setLinkSite("sitename.user19.com");
        user19 .setLinkGitHub("user19.github.com");
        user19.setLinkVk("vk.com/user19");
        user19.setAbout("I am User19");
        user19.setNickname("user19NickName");
        user19 .setLastUpdateDateTime(LocalDateTime.now());
        user19.setRole(userRole);
        userService.persist(user19);

        User user20 = new User();
        user20.setEmail("user20@user.com");
        user20.setPassword("admin20");
        user20.setFullName(" User user20");
        user20.setPersistDateTime(LocalDateTime.now());
        user20.setIsEnabled(true);
        user20.setCity("CitiName20");
        user20.setImageLink("user20.image.link.com");
        user20 .setLinkSite("sitename.user20.com");
        user20 .setLinkGitHub("user20.github.com");
        user20.setLinkVk("vk.com/user20");
        user20.setAbout("I am User20");
        user20.setNickname("user20NickName");
        user20 .setLastUpdateDateTime(LocalDateTime.now());
        user20.setRole(userRole);
        userService.persist(user20);

        User user21 = new User();
        user21.setEmail("user21@user.com");
        user21.setPassword("admin21");
        user21.setFullName(" User user21");
        user21.setPersistDateTime(LocalDateTime.now());
        user21.setIsEnabled(true);
        user21.setCity("CitiName21");
        user21.setImageLink("user21.image.link.com");
        user21 .setLinkSite("sitename.user21.com");
        user21 .setLinkGitHub("user21.github.com");
        user21.setLinkVk("vk.com/user21");
        user21.setAbout("I am User21");
        user21.setNickname("user21NickName");
        user21 .setLastUpdateDateTime(LocalDateTime.now());
        user21.setRole(userRole);
        userService.persist(user21);

        User user22 = new User();
        user22.setEmail("user22@user.com");
        user22.setPassword("admin22");
        user22.setFullName(" User user22");
        user22.setPersistDateTime(LocalDateTime.now());
        user22.setIsEnabled(true);
        user22.setCity("CitiName22");
        user22.setImageLink("user22.image.link.com");
        user22 .setLinkSite("sitename.user22.com");
        user22 .setLinkGitHub("user22.github.com");
        user22.setLinkVk("vk.com/user22");
        user22.setAbout("I am User22");
        user22.setNickname("user22NickName");
        user22 .setLastUpdateDateTime(LocalDateTime.now());
        user22.setRole(userRole);
        userService.persist(user22);

        User user23 = new User();
        user23.setEmail("user23@user.com");
        user23.setPassword("admin23");
        user23.setFullName(" User user23");
        user23.setPersistDateTime(LocalDateTime.now());
        user23.setIsEnabled(true);
        user23.setCity("CitiName23");
        user23.setImageLink("user23.image.link.com");
        user23 .setLinkSite("sitename.user23.com");
        user23 .setLinkGitHub("user23.github.com");
        user23.setLinkVk("vk.com/user23");
        user23.setAbout("I am User23");
        user23.setNickname("user23NickName");
        user23 .setLastUpdateDateTime(LocalDateTime.now());
        user23.setRole(userRole);
        userService.persist(user23);

        User user24 = new User();
        user24.setEmail("user24@user.com");
        user24.setPassword("admin24");
        user24.setFullName(" User user24");
        user24.setPersistDateTime(LocalDateTime.now());
        user24.setIsEnabled(true);
        user24.setCity("CitiName24");
        user24.setImageLink("user24.image.link.com");
        user24 .setLinkSite("sitename.user24.com");
        user24 .setLinkGitHub("user24.github.com");
        user24.setLinkVk("vk.com/user24");
        user24.setAbout("I am User24");
        user24.setNickname("user24NickName");
        user24 .setLastUpdateDateTime(LocalDateTime.now());
        user24.setRole(userRole);
        userService.persist(user24);

        User user25 = new User();
        user25.setEmail("user25@user.com");
        user25.setPassword("admin25");
        user25.setFullName(" User user25");
        user25.setPersistDateTime(LocalDateTime.now());
        user25.setIsEnabled(true);
        user25.setCity("CitiName25");
        user25.setImageLink("user25.image.link.com");
        user25 .setLinkSite("sitename.user25.com");
        user25 .setLinkGitHub("user25.github.com");
        user25.setLinkVk("vk.com/user25");
        user25.setAbout("I am User25");
        user25.setNickname("user25NickName");
        user25 .setLastUpdateDateTime(LocalDateTime.now());
        user25.setRole(userRole);
        userService.persist(user25);

        User user26 = new User();
        user26.setEmail("user26@user.com");
        user26.setPassword("admin26");
        user26.setFullName(" User user26");
        user26.setPersistDateTime(LocalDateTime.now());
        user26.setIsEnabled(true);
        user26.setCity("CitiName26");
        user26.setImageLink("user26.image.link.com");
        user26 .setLinkSite("sitename.user26.com");
        user26 .setLinkGitHub("user26.github.com");
        user26.setLinkVk("vk.com/user26");
        user26.setAbout("I am User26");
        user26.setNickname("user26NickName");
        user26 .setLastUpdateDateTime(LocalDateTime.now());
        user26.setRole(userRole);
        userService.persist(user26);

        User user27 = new User();
        user27.setEmail("user27@user.com");
        user27.setPassword("admin27");
        user27.setFullName(" User user27");
        user27.setPersistDateTime(LocalDateTime.now());
        user27.setIsEnabled(true);
        user27.setCity("CitiName27");
        user27.setImageLink("user27.image.link.com");
        user27 .setLinkSite("sitename.user27.com");
        user27 .setLinkGitHub("user27.github.com");
        user27.setLinkVk("vk.com/user27");
        user27.setAbout("I am User27");
        user27.setNickname("user27NickName");
        user27 .setLastUpdateDateTime(LocalDateTime.now());
        user27.setRole(userRole);
        userService.persist(user27);

        User user28 = new User();
        user28.setEmail("user28@user.com");
        user28.setPassword("admin28");
        user28.setFullName(" User user28");
        user28.setPersistDateTime(LocalDateTime.now());
        user28.setIsEnabled(true);
        user28.setCity("CitiName28");
        user28.setImageLink("user28.image.link.com");
        user28 .setLinkSite("sitename.user28.com");
        user28 .setLinkGitHub("user28.github.com");
        user28.setLinkVk("vk.com/user28");
        user28.setAbout("I am User28");
        user28.setNickname("user28NickName");
        user28 .setLastUpdateDateTime(LocalDateTime.now());
        user28.setRole(userRole);
        userService.persist(user28);

        User user29 = new User();
        user29.setEmail("user29@user.com");
        user29.setPassword("admin29");
        user29.setFullName(" User user29");
        user29.setPersistDateTime(LocalDateTime.now());
        user29.setIsEnabled(true);
        user29.setCity("CitiName29");
        user29.setImageLink("user29.image.link.com");
        user29 .setLinkSite("sitename.user29.com");
        user29 .setLinkGitHub("user29.github.com");
        user29.setLinkVk("vk.com/user29");
        user29.setAbout("I am User29");
        user29.setNickname("user29NickName");
        user29 .setLastUpdateDateTime(LocalDateTime.now());
        user29.setRole(userRole);
        userService.persist(user29);

        User user30 = new User();
        user30.setEmail("user30@user.com");
        user30.setPassword("admin30");
        user30.setFullName(" User user30");
        user30.setPersistDateTime(LocalDateTime.now());
        user30.setIsEnabled(true);
        user30.setCity("CitiName30");
        user30.setImageLink("user30.image.link.com");
        user30 .setLinkSite("sitename.user30.com");
        user30 .setLinkGitHub("user30.github.com");
        user30.setLinkVk("vk.com/user30");
        user30.setAbout("I am User30");
        user30.setNickname("user30NickName");
        user30 .setLastUpdateDateTime(LocalDateTime.now());
        user30.setRole(userRole);
        userService.persist(user30);

        User user31 = new User();
        user31.setEmail("user31@user.com");
        user31.setPassword("admin31");
        user31.setFullName(" User user31");
        user31.setPersistDateTime(LocalDateTime.now());
        user31.setIsEnabled(true);
        user31.setCity("CitiName31");
        user31.setImageLink("user31.image.link.com");
        user31 .setLinkSite("sitename.user31.com");
        user31 .setLinkGitHub("user31.github.com");
        user31.setLinkVk("vk.com/user31");
        user31.setAbout("I am User31");
        user31.setNickname("user31NickName");
        user31 .setLastUpdateDateTime(LocalDateTime.now());
        user31.setRole(userRole);
        userService.persist(user31);

        User user32 = new User();
        user32.setEmail("user32@user.com");
        user32.setPassword("admin32");
        user32.setFullName(" User user32");
        user32.setPersistDateTime(LocalDateTime.now());
        user32.setIsEnabled(true);
        user32.setCity("CitiName32");
        user32.setImageLink("user32.image.link.com");
        user32 .setLinkSite("sitename.user32.com");
        user32 .setLinkGitHub("user32.github.com");
        user32.setLinkVk("vk.com/user32");
        user32.setAbout("I am User32");
        user32.setNickname("user32NickName");
        user32 .setLastUpdateDateTime(LocalDateTime.now());
        user32.setRole(userRole);
        userService.persist(user32);

        User user33 = new User();
        user33.setEmail("user33@user.com");
        user33.setPassword("admin33");
        user33.setFullName(" User user33");
        user33.setPersistDateTime(LocalDateTime.now());
        user33.setIsEnabled(true);
        user33.setCity("CitiName33");
        user33.setImageLink("user33.image.link.com");
        user33 .setLinkSite("sitename.user33.com");
        user33 .setLinkGitHub("user33.github.com");
        user33.setLinkVk("vk.com/user33");
        user33.setAbout("I am User33");
        user33.setNickname("user33NickName");
        user33 .setLastUpdateDateTime(LocalDateTime.now());
        user33.setRole(userRole);
        userService.persist(user33);

        User user34 = new User();
        user34.setEmail("user34@user.com");
        user34.setPassword("admin34");
        user34.setFullName(" User user34");
        user34.setPersistDateTime(LocalDateTime.now());
        user34.setIsEnabled(true);
        user34.setCity("CitiName34");
        user34.setImageLink("user34.image.link.com");
        user34 .setLinkSite("sitename.user34.com");
        user34 .setLinkGitHub("user34.github.com");
        user34.setLinkVk("vk.com/user34");
        user34.setAbout("I am User34");
        user34.setNickname("user34NickName");
        user34 .setLastUpdateDateTime(LocalDateTime.now());
        user34.setRole(userRole);
        userService.persist(user34);

        User user35 = new User();
        user35.setEmail("user35@user.com");
        user35.setPassword("admin35");
        user35.setFullName(" User user35");
        user35.setPersistDateTime(LocalDateTime.now());
        user35.setIsEnabled(true);
        user35.setCity("CitiName35");
        user35.setImageLink("user35.image.link.com");
        user35 .setLinkSite("sitename.user35.com");
        user35 .setLinkGitHub("user35.github.com");
        user35.setLinkVk("vk.com/user35");
        user35.setAbout("I am User35");
        user35.setNickname("user35NickName");
        user35 .setLastUpdateDateTime(LocalDateTime.now());
        user35.setRole(userRole);
        userService.persist(user35);

        User user36 = new User();
        user36.setEmail("user36@user.com");
        user36.setPassword("admin36");
        user36.setFullName(" User user36");
        user36.setPersistDateTime(LocalDateTime.now());
        user36.setIsEnabled(true);
        user36.setCity("CitiName36");
        user36.setImageLink("user36.image.link.com");
        user36 .setLinkSite("sitename.user36.com");
        user36 .setLinkGitHub("user36.github.com");
        user36.setLinkVk("vk.com/user36");
        user36.setAbout("I am User36");
        user36.setNickname("user36NickName");
        user36 .setLastUpdateDateTime(LocalDateTime.now());
        user36.setRole(userRole);
        userService.persist(user36);

        User user37 = new User();
        user37.setEmail("user37@user.com");
        user37.setPassword("admin37");
        user37.setFullName(" User user37");
        user37.setPersistDateTime(LocalDateTime.now());
        user37.setIsEnabled(true);
        user37.setCity("CitiName37");
        user37.setImageLink("user37.image.link.com");
        user37 .setLinkSite("sitename.user37.com");
        user37 .setLinkGitHub("user37.github.com");
        user37.setLinkVk("vk.com/user37");
        user37.setAbout("I am User37");
        user37.setNickname("user37NickName");
        user37 .setLastUpdateDateTime(LocalDateTime.now());
        user37.setRole(userRole);
        userService.persist(user37);

        User user38 = new User();
        user38.setEmail("user38@user.com");
        user38.setPassword("admin38");
        user38.setFullName(" User user38");
        user38.setPersistDateTime(LocalDateTime.now());
        user38.setIsEnabled(true);
        user38.setCity("CitiName38");
        user38.setImageLink("user38.image.link.com");
        user38 .setLinkSite("sitename.user38.com");
        user38 .setLinkGitHub("user38.github.com");
        user38.setLinkVk("vk.com/user38");
        user38.setAbout("I am User38");
        user38.setNickname("user38NickName");
        user38 .setLastUpdateDateTime(LocalDateTime.now());
        user38.setRole(userRole);
        userService.persist(user38);

        User user39 = new User();
        user39.setEmail("user39@user.com");
        user39.setPassword("admin39");
        user39.setFullName(" User user39");
        user39.setPersistDateTime(LocalDateTime.now());
        user39.setIsEnabled(true);
        user39.setCity("CitiName39");
        user39.setImageLink("user39.image.link.com");
        user39 .setLinkSite("sitename.user39.com");
        user39 .setLinkGitHub("user39.github.com");
        user39.setLinkVk("vk.com/user39");
        user39.setAbout("I am User39");
        user39.setNickname("user39NickName");
        user39 .setLastUpdateDateTime(LocalDateTime.now());
        user39.setRole(userRole);
        userService.persist(user39);

        User user40 = new User();
        user40.setEmail("user40@user.com");
        user40.setPassword("admin40");
        user40.setFullName(" User user40");
        user40.setPersistDateTime(LocalDateTime.now());
        user40.setIsEnabled(true);
        user40.setCity("CitiName40");
        user40.setImageLink("user40.image.link.com");
        user40 .setLinkSite("sitename.user40.com");
        user40 .setLinkGitHub("user40.github.com");
        user40.setLinkVk("vk.com/user40");
        user40.setAbout("I am User40");
        user40.setNickname("user40NickName");
        user40 .setLastUpdateDateTime(LocalDateTime.now());
        user40.setRole(userRole);
        userService.persist(user40);
    }
}
